window:
  padding:
   x: 8
   y: 8
  opacity: 0.97

font:
  size: 12
  normal:
    family: JetBrainsMono Nerd Font
    # style:  Regular

colors:

  primary:
    background: '#0e090f'
    foreground: '#dedede'

  normal:
    black:   '#15121c'
    red:     '#cb5760'
    green:   '#999f63'
    yellow:  '#d4a067'
    blue:    '#6c90a8'
    magenta: '#776690'
    cyan:    '#528a9b'
    white:   '#eeffff'

  bright:
    black:   '#727480'
    red:     '#cb5760'
    green:   '#999f63'
    yellow:  '#d4a067'
    blue:    '#6c90a8'
    magenta: '#776690'
    cyan:    '#528a9b'
    white:   '#eeffff'

